# This file contains values from Cookiecutter

default_context:
  project_name: "Generative Interface"
  repo_name: "GenerativeInterface"
  description: "Interface to interact with several generative models."
  organization: "TU/e"
  license: "MIT"
  organization_email: "none@none.pt"
  line_length: "120"
  python_minimal_version: "3.9"
